POST http://localhost:8080/image-handler HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJpbWFnZS1zdG9yZS1hcGkiLCJpYXQiOjE3NDM1NzA3ODEsImV4cCI6MTc0MzU4NTE4MSwic3ViIjoid2FyZG9nMUBnbWFpbC5jb20ifQ.udaBeSrCijbJ51SglwzIKSHXFQhV3o5JFgwm2t3_sEY

{
    "fileName": "cachorro.png",
    "percentage": 50
}